apiVersion: v2
name: hello-world
description: A Helm chart to deploy hello world
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common-helm-chart
    version: 0.1.0
    repository: file://../../common-helm-chart
