replicaCount: 1
containerPort: 8080
targetPort: 8080
servicePort: 80
env:
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: DB_PASSWORD
image:
  repository: jumapaul/hello-world
  pullPolicy: IfNotPresent
  tag: "c9d8a3d"
ingress:
  host: "hello-world.com"
secretVolume:
  name: app-secret-vol
  mountPath: "/app/crds"
  secretName: db-secret
serviceType: ClusterIP
configMap:
  data:
    DB_URL: "jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres"