replicaCount: 1
containerPort: 8082
targetPort: 8082
servicePort: 80
serviceType: NodePort
image:
  repository: jumapaul/hello-world-2
  pullPolicy: IfNotPresent
  tag: "0f6b38d"
probes:
  liveness:
    path: /actuator/health/liveness
    port: 8082
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    port: 8082
    periodSeconds: 10
    failureThreshold: 3
