apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    DB_PASSWORD: AgAuxnhTVd1zXN7qCtaAMU9E6RjTXOc5xsGI/FcfKy4naFPqWoIkqT1cW0BacDZlay1UFjWmhNYVFaUOD1/aDm/5lid6rLCKa1tP+7W/+446XRXnK9sk9xrutdB48tKBt65OLrfMxgvZchbqLMQmVV/x/5XwZNTVR+Z+b425BPQ3NmHMjDHhGlGFeAMcmkrPAw9AC8xaLy+rs7DqlfY/yZNcHV6IpjOs7Oq0rlYpQXptG63UDucdCWQkeNDYmTR98Fv+dGQobSZl2kMqtif8+K/d3h2Pv0ult1/QbndcKJp5MVsm0r4nT7jdnGY1zhzvKtd4ofqsqv9JBXh/33SdqC89+9TEpjsA9mlm+KOaOZLosw45lRoWZdAInisK/5ozFDecOVZ0oJUZAuRO0V9b1webJIxAX9dfG2ufYIZJyGaVZCcAz+smMN7Wj+LoliZoarCCha2Ws7rlo+X0yiJd2O6ussMwi4Gm7mNSs67OKrLL4bw+toAbr5Vh+OlTC09aSKCU79FeiY1QH9eV6J0GfpARIRC/rqfrpsBUaWUPromRTvpOuHHh1hxFjwHiHFSYlXdOGL/JCx5A045TbVKIYvA41SETNmsYSct8IGry9vdhTGd50Fm5u2WXRuAN8O5w/qFDmL0hrjU9bEmvPzHDEA9lUIjtJipPWW35rSaQbNU8qU6McA152qWiNJ2Wbz30UkTuabityG7sr1VTjQ==
    DB_USERNAME: AgBi6X/c5ifSKEmU+EwvVN0PZ9h6XDPBTqT6v5Jr6iwl0T9LJURts2jivT4MZpZx+oo6zf9s1EwEljwgrE5qDaekZgnVOdbfYDJVzHTZtLy8C4QTYMOUli0Eep0VNLXJv9XTVjkRSdwo54vXSwoaSaXscFyO0AIb0favv1dNTJIwtety/hZscWw6ojDj7SyT4gjqcwu+k4Jcidfoa5yAWIYlVvi134+qAAioaojZpMbKMycs9NXf5JphPPBGGiv4lJZBImett3WYiDcQZ7m2gj2Ci9DWBGNQmxhXnpK2Hd7gJbYRy2jYnFKwEiUY+r8hFX3EUDHcjIXfr3zf8tCr94VZNYkYJZYXYreyixfthWEYjVRnE8IqxfFz0YAjiJ0vMRcsZPl7EEOxwbK/6jjzx19AEtHsQo58vg8G95hWb4nrS6VVxJEEt9CANAoox2lHKvggf6PxrLNCPjoPhvpzeXPhlGmuhiV6OejHvsq+iqsQpuVpRbtSSkTfA5sQwtN9WazexfydHCjL14yfIBHPmPVTazBDUuWJR7nFP4hkXvSXPALZb7oNSxei9zBxV9HYkl0Qpe70u5EPTJVlx/ftUN+ki6PDyhOwABmAO6FPAnPd8Izm9ZMso13IY3U+7m0jKlpzJ0OqElTTR7tpUiII4DYqV2rnlCIcoyzsWiJEr5E6VCDNldSEU1fzZ9Bekqx3vH2kgbs3wBN4DhWFKWgR3DnAHCv3RNjzVmo3gY7k3w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret
    type: Opaque