apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: db-secret
spec:
  encryptedData:
    DB_PASSWORD: AgAmZDprddlgKsPGB2F94waDNNzDEODKg9uMvbYDVDYvTS/DrqZILx5LrijsoGFWETMUM7AkCebgZsvkko6406imzuRLHjMp0W4uwS9je9TWa2GXj8o1Y4pyAKb2VQEFK5VuRb0j3FCOtRMQpRayyiyNTX+bhGHaSqgymZgvv2LeLAdigmVv1/HjbVMh8gM0rO1/gBB11FHMzHzm+7aPxeHmOMLGPHTISXIPYZ/c5edYJXwQJJSswN/N0gB2d5kUQmsOamjFVH6q3riyHDxn3smYsFor5AnTThz1GXNP6S+xCprVADny/5xipgeddlrm3VwKEG6FSMxki88zMyfg6mgcnq5KDrbmSq13rOv5t7sWIaQsm9oymb1VcdNX/+c4vBuW6uLtrX7LKwFpimeyYvTO4D6e4zIpfN6cz8Y08W416XSmIPv1q1ozxXq0TbfGVF65apXdatRzR+4UWPU3uBQHM9OuYCh49qsRTvCJrHrB13vBHZBMtgSJ5C9e5TmeP/EMu1pjEBfKaWmdZSbK3z32kBU6VFrbrsOdV9ikGZr0p0wGr09zZgbGAHffCia3iYAucZ4FMIZfb25vp0UchZVaf33gVYhoQYrrqW9rqq33BfgtUgDcJLvF3WUrIGXyAkboRqua8jC20tdEg4lcYGUm4IMnovo+W7o6aOGXD39qA+vskw1y1Ku25gku76i8UCL9mLgHM7NPUwU=
    DB_USERNAME: AgBH4IuFUHoT/oK7W773IH3N4xZ8KrXvoURgLPRe11ZEHxi8FbW/VUzk/YF5LiuNPLw07ZRZRg68xyylJdUadboRRlIVDTlUijkipeU5HTG8y84rRoNrjbi76Z8CG9pjjpoyMwEqVBi+QG40jgOk1vpTMNOiuEhGHCIL13fPOxydsAUiP497jclCAjM8lxX3v+/PWVFt+veLSw78DY+zNXbAaWorM6Y1hy58TrEyAQ+pgxCa3w4R85GlJp9IlNNiNAtlgCut9hGQGKNet6DLSsHMHfKk1bI6QBKtY5E433mWxGlqO26QYOL3bERk1XuRMl9jo+77yWZLZF8N10+Ij9AyvsWnk4GnGpjErn33b0oGlTUtU1Zh+vVNyEyDcNfbQjsuYENzkcAEJd8NR1FBY4uRgYBaHQjGpWIvYo6il/0haT9EelppK8ZTFKFCsDyBpsCdXbvmdiHXoYcxM4FDr8F7KoMweg2j/UhS9u1kM1+jiAyOQHCsWSp5ATg8hm3+U2KVeXZk1v748WxzqmYpb4rgN4KZNrkELDXQIHlQqCpTNqhCn/1TAZv4xi+Id90c8naHsCapvvO6W1X3LODr16re+nJ/J7vkyyWeBMbf06ti0+vX6BaI+ldjrZyoHHvIZ/krz61t9lFqQKEVRW5XYv7cm8qpGZhKmsziygkQ5P8tbX78XhV2+VBB0WMR/1/yTgfeWxbArLIV+gA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: db-secret
    type: Opaque

